services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        API_PORT: "${API_PORT}"
    environment:
      - PORT=${API_PORT}
      - CRON_SCHEDULE=${API_CRON_SCHEDULE}
      - STREAM_PING_TIMEOUT=${API_STREAM_PING_TIMEOUT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./data:/app/data
    networks:
      - csm-network
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        REACT_APP_API_URL: "${REACT_APP_API_URL}"
        REACT_APP_HEALTH_CHECK_INTERVAL: "${REACT_APP_HEALTH_CHECK_INTERVAL}"
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - server
    networks:
      - csm-network
    restart: unless-stopped

networks:
  csm-network:
    driver: bridge
