version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        API_PORT: "${API_PORT}"
    environment:
      - PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./server/prisma:/app/dist/server/prisma
    networks:
      - csm-network
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        REACT_APP_API_URL: "${REACT_APP_API_URL}"
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - server
    networks:
      - csm-network
    restart: unless-stopped

networks:
  csm-network:
    driver: bridge
