version: "3"
services:
  server:
    image: cam_stream_manager-server:latest
    environment:
      - PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./prisma:/app/dist/server/prisma
    networks:
      - csm-network
    restart: unless-stopped

  client:
    image: cam_stream_manager-client:latest
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - server
    networks:
      - csm-network
    restart: unless-stopped

networks:
  csm-network:
    driver: bridge
