export type {
  PlaylistInfoDto as PlaylistInfo,
  StreamDashboardDto as StreamDashboard,
  EventDto,
  Page,
  GroupDto as Group,
  NewGroupDto as NewGroup,
  UpdateGroupDto as UpdateGroup,
  PlaylistDto as Playlist,
  NewPlaylistDto as NewPlaylist,
  UpdatePlaylistDto as UpdatePlaylist,
  ResponsiblePersonDto as ResponsiblePerson,
  NewResponsiblePersonDto as NewResponsiblePerson,
  UpdateResponsiblePersonDto as UpdateResponsiblePerson,
  StreamDto as Stream,
  NewStreamDto as NewStream,
  UpdateStreamDto as UpdateStream,
  UserDto as User,
  NewUserDto as NewUser,
  UpdateUserDto as UpdateUser,
  UpdateUserPasswordDto as UpdateUserPassword,
} from '@shared/types';
